name: Run Spectral on API Specs

on:
  - pull_request

jobs:
  build:
    name: Run Spectral
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v3

      - name: Show content
        run: find .
        
      # Run Spectral
      - name: Spectral Linting
        uses: stoplightio/spectral-action@v0.8.10
        with:
          file_glob: '*.json'
